--Q27--
SELECT COUNT(*) AS SL_GV, SUM(LUONG) AS TONGLUONG
FROM GIAOVIEN

--Q28--
SELECT MABM, COUNT(MAGV) AS SLGV, AVG(LUONG) AS LUONGTB
FROM GIAOVIEN
GROUP BY MABM

--Q29--
SELECT CD.TENCD, COUNT(DT.MADT) AS SLDT
FROM DETAI AS DT INNER JOIN CHUDE AS CD ON DT.MACD = CD.MACD
GROUP BY CD.TENCD

--Q30--
SELECT GV.MAGV,GV.HOTEN, COUNT(DISTINCT TG.MADT) AS SLDT
FROM THAMGIADT AS TG, GIAOVIEN AS GV WHERE TG.MAGV = GV.MAGV
GROUP BY GV.MAGV, GV.HOTEN

--Q31--
SELECT DT.GVCNDT, GV.HOTEN, COUNT(DT.MADT)
FROM DETAI AS DT, GIAOVIEN AS GV WHERE DT.GVCNDT = GV.MAGV
GROUP BY DT.GVCNDT, GV.HOTEN

--Q32--
SELECT NT.MAGV, GV.HOTEN, COUNT(NT.TEN) AS SO_NT
FROM NGUOI_THAN AS NT, GIAOVIEN AS GV WHERE NT.MAGV = GV.MAGV
GROUP BY NT.MAGV, GV.HOTEN

--Q33-
SELECT GV.HOTEN 
FROM THAMGIADT AS TG, GIAOVIEN AS GV WHERE TG.MAGV = GV.MAGV
GROUP BY TG.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT TG.MADT) >= 3

--Q34--
SELECT COUNT(TG.MAGV) AS SLGV
FROM DETAI AS DT, THAMGIADT AS TG 
WHERE TENDT = N'HTTT quản lý các trường ĐH' AND DT.MADT = TG.MADT
GROUP BY TG.MADT
